@HostAddress=http://localhost:10000

POST {{HostAddress}}/jobs/5d361ddb-9103-4adf-a4ef-e6f653f4e22e/status-update/completed

###

POST {{HostAddress}}/jobs/5d361ddb-9103-4adf-a4ef-e6f653f4e22e/status-update/inprogress